services:
  redis:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
  app:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHECK_INTERVAL=20
    depends_on:
      - redis
