services:
    app:
        build: .
        environment:
            - DISCORD_WH=${DISCORD_WH}
            - DISCORD_TOKEN=${DISCORD_TOKEN}
        deploy:
            resources:
                limits:
                    # cpus: '0.50'
                    memory: 500M
        restart: "always"
