services:
  app:
    build: .
    environment:
    -   DISCORD_WH=${DISCORD_WH}
    -   DISCORD_TOKEN=${DISCORD_TOKEN}
    volumes:
    -   "./docker:/root/.series-scraping"
    deploy:
      resources:
        limits:
          memory: 500M
    restart: "always"
