services:
  app:
    build: .
    environment:
    -   DISCORD_WH=${DISCORD_WH}
    -   DISCORD_TOKEN=${DISCORD_TOKEN}
    -   DATABASE_FILE=/root/database.json
    volumes:
    -   "./docker:/root/"
    deploy:
      resources:
        limits:
          memory: 500M
    restart: "always"
