services:
    redis:
        image: redis
        deploy:
            resources:
                limits:
                    memory: 50M
    app:
        build: .
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - DISCORD_WH=${DISCORD_WH}
        depends_on:
            - redis
        deploy:
            resources:
                limits:
                    # cpus: '0.50'
                    memory: 800M
