[[series]]
title = "Martial Peak"
url = "https://manhuaplus.com/manga/martial-peak/"
store_key = "martial-peak"
discord_wh = "https://discord.com/api/webhooks/1046665729166020648/BhO1w3r65bDEol449m9H39qrEbfOacFSq6jCR4RawMUviIozGqq3CNNDn5c5g3PvBDGV"
check_interval = 300

[[series]]
title = "Magic Demon Emperor"
url = "https://manhuaplus.com/manga/demon-magic-emperor/"
store_key = "magic-demon-emperor"
discord_wh = "https://discord.com/api/webhooks/1046665729166020648/BhO1w3r65bDEol449m9H39qrEbfOacFSq6jCR4RawMUviIozGqq3CNNDn5c5g3PvBDGV"
check_interval = 43200 # 12 hours
