[tool.poetry]
name = "manhuaplus-scraping"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [{ include = "manhuaplus_scraping" }]

[tool.poetry.dependencies]
python = "^3.10"
playwright = "^1.28.0"
redis = "^4.3.5"
requests = "^2.28.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
