version = 1
disable_existing_loggers = false

# [root]
# level = "INFO"
# handlers = ["default", "discord"]

[formatters]

[formatters.default]
"()" = "manhuaplus_scraping.CustomFormatter"
format = '[ %(asctime)s ] [ %(author)s ] [ %(levelname)s ] %(message)s'

[formatters.discord]
"()" = "manhuaplus_scraping.CustomFormatter"
format = '>>> **[ %(author)s ] [ %(levelname)s ]** %(message)s'

[handlers]

[handlers.default]
class = "logging.StreamHandler"
formatter = "default"

[handlers.discord]
class = "manhuaplus_scraping.DiscordLoggingHandler"
formatter = "discord"

[loggers]

[loggers."manhuaplus_scraping"]
level = "INFO"
handlers = ["default", "discord"]
