[logging]
version = 1
disable_existing_loggers = false

[logging.formatters]

[logging.formatters.default]
"()" = "manhuaplus_scraping.logging.CustomFormatter"
format = '[ %(asctime)s ] [ %(author)s ] [ %(levelname)s ] %(message)s'

[logging.formatters.discord]
"()" = "manhuaplus_scraping.logging.CustomFormatter"
format = '>>> **[ %(author)s ] [ %(levelname)s ]** %(message)s'

[logging.handlers]

[logging.handlers.default]
class = "logging.StreamHandler"
formatter = "default"

[logging.handlers.discord]
class = "manhuaplus_scraping.logging.DiscordLoggingHandler"
formatter = "discord"

[logging.loggers]

[logging.loggers.manhuaplus_scraping]
level = "INFO"
handlers = ["default", "discord"]

[manhua]

[[manhua.series]]
title = "Martial Peak"
url = "https://manhuaplus.com/manga/martial-peak/"
store_key = "martial-peak"
check_interval = [ 2, 3, 10, 14, 15, 16, 20, 22 ]
enabled = true

[[manhua.series]]
title = "Heavens Devourer"
url = "https://manhuaplus.com/manga/heavens-devourer/"
store_key = "heavens-devourer"
check_interval = [ 22 ]
enabled = false
